### ISSUE TITLE
Links in the readme are broken

### ISSUE THREAD

**Issue by bootstraponline** [walmartlabs/walmart-cla#25]
- https://sde.walmart.com/docs/open-source/index.html
- https://sde.walmart.com/

**Comment by mosabua** [comment]
Those are walmart internal website and work fine.

**Comment by mosabua** [comment]
We now launched the website code.walmartlabs.com publically. Check it out! There is lots more coming. SDE is an internal website

**Comment by ghost** [comment]
Thank you a lot! It is a very interesting site and especially the "mission" page could have a lighthouse effect.

Reading that site, I understand that the signed CLA should be send to `opensource@...`? In that case the "Contact Us" section might be a bit misleading -- from it I assumed that the CLA should *not* be send to that address.

**Comment by mosabua** [comment]
You can send a corporate CLA to that email .. yes. I will get that .. or for individual contrib you can sign in github yourself
